### ISSUE TITLE
Create User with password

### ISSUE THREAD

**Issue by guiguitatu** [petersudario/petmania#39]
Quando eu vou a criar um usuário pelo dashboard do admin, ele diz que não foi possível criar pois não foi informado uma senha, assim não sendo possível adicionar o usuário. Também não foi possível criar um pet, pois este seria necessário um dono, não conseguindo criar um dono não é possível criar um pet.
![imagem_2024-05-13_111639519](https://github.com/petersudario/petmania/assets/130491722/82c7af1d-2d15-40a6-8043-baac4cb0f2ae)
![imagem_2024-05-13_111650301](https://github.com/petersudario/petmania/assets/130491722/5b8ee9fb-7442-4e60-aae0-ed1456a2f557)

**Comment by petersudario** [comment]
Issue resolvida. Dono de pet foi descartado
